In [1]:
import numpy as np

In [4]:
my_array = np.array([1,2,3])
print(my_array)

[1 2 3]


In [8]:
my_2d_array = np.array([[1,2,3], [4,5,6]])
print(my_2d_array)

[[1 2 3]
 [4 5 6]]


In [9]:
# 1d array
my_array[0]

1

In [11]:
# 2d array
my_2d_array[1, 2]

# first term is the dimensionality 
# second term is the index in that dimension

6

## Pandas

In [13]:
import pandas as pd

In [17]:
ins_data = {
    'name': ['Steph', 'Jamie', 'David', 'John', 'Lloyd'],
    'favourite_number': [2, 5, 7, 12, 90]
}

type(ins_data)

dict

In [20]:
instructors_dataframe = pd.DataFrame(ins_data)
instructors_dataframe

name  favourite_number
0  Steph                 2
1  Jamie                 5
2  David                 7
3   John                12
4  Lloyd                90

In [23]:
# pd.DataFrame? - to get help file

# pd.DataFrame - "Shift + Tab" to get the arguments

In [28]:
ins_data = pd.DataFrame({
    'name': ['Steph', 'Jamie', 'David', 'John', 'Lloyd'],
    'favourite_number': [2, 5, 7, 12, 90]},
    index = [1,2,3,4,5]
)

print(ins_data)

    name  favourite_number
1  Steph                 2
2  Jamie                 5
3  David                 7
4   John                12
5  Lloyd                90
